/**
 * Created by Guang on 16/4/26.
 */

"use strict";

export const KEEP = {
    ADD_KEEP : 'ADD_KEEP',
    ADD_SUCCESS : "ADD_SUCCESS",
    ADD_ERROR : "ADD_ERROR",
    KEEP_CLEAR : 'KEEP_CLEAR',
    LEAD_KEEP : 'LEAD_KEEP',
    LEAD_SUCCESS : 'LEAD_SUCCESS',
    LEAD_ERROR : 'LEAD_ERROR',
};

export const LOGIN ={
    LOGIN : 'LOGIN',
    LOGIN_ERROR : 'LOGIN_ERROR',
    LOGOUT : 'LOGOUT'
};

export const CHILD = {
    CHILD_LOAD :'CHILD_LOAD',
    CHILD_LOAD_SUCCESS :'CHILD_LOAD_SUCCESS',
    CHILD_LOAD_ERROR :'CHILD_LOAD_ERROR',
    CHILD_ADD :'CHILD_ADD',
    CHILD_ADD_SUCCESS :'CHILD_ADD_SUCCESS',
    CHILD_ADD_ERROR :'CHILD_ADD_ERROR'
}