# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'KeepOnGrowing' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
    pod 'React', :path => '../node_modules/react-native', :subspecs => [
      'Core',
      'RCTImage',
      'RCTNetwork',
      'RCTText',
      'RCTWebSocket',
    ]
    pod 'CodePush', :path => '../node_modules/react-native-code-push'
    pod 'react-native-material-kit', :path => '../node_modules/react-native-material-kit'

  # Pods for KeepOnGrowing

#target 'KeepOnGrowingTests' do
#inherit! :search_paths
    # Pods for testing
    # end

end
